baseURL = 'https://ig-site.com/'
languageCode = 'et'
title = 'Berghoff'
theme = 'berghoff'

defaultContentLanguage = 'et'
[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files

[languages]
  [languages.et]
    contentDir = 'content/et'
    languageName = 'ET'
    weight = 1
    [languages.et.menu]
      [[languages.et.menu.main]]
        identifier = 'rules'
        name = 'Reeglid'
        url = '/'
        weight = 10
      [[languages.et.menu.main]]
        name = 'Tooted'
        url = '/products/'
        weight = 20
      [[languages.et.menu.main]]
        name = 'Eripakkumised'
        url = '/special-promotion/'
        weight = 30
  [languages.ru]
    contentDir = 'content/ru'
    languageName = 'RU'
    weight = 2
    [languages.ru.menu]
      [[languages.ru.menu.main]]
        identifier = 'rules'
        name = 'правила'
        url = '/'
        weight = 10
      [[languages.ru.menu.main]]
        name = 'продукты'
        url = '/products/'
        weight = 20
      [[languages.ru.menu.main]]
        name = 'специальные предложения'
        url = '/special-promotion/'
        weight = 30